source 'https://rubygems.org'

gem 'daemons'
gem 'scrobbler'
gem 'grackle'
gem 'simple-rss'
gem 'sanitize'
gem 'whois'
gem 'activesupport', '>= 3.2.12'
gem 'actionpack', '>= 3.2.12'
gem 'activerecord', '>= 3.2.12'
gem 'i18n'
gem 'sqlite3'
gem 'isaac'
